### ISSUE TITLE
What's the point of the if condition if the result of each condition will do the same thing?!

### ISSUE THREAD

**Issue by IsraaMoqbel** [FACG5/SSIA-API-WeatherApp#12]
https://github.com/FACG5/SSIA-API-WeatherApp/blob/aa2e3629585cfe02570e0e38d7c282e57823f3f4/public/js/logic.js#L14

```     // ready
        var result = JSON.parse(xhr.responseText);
        cb(result);
      } else if (xhr.status == 404) {
        // error
        var result = JSON.parse(xhr.responseText);
        cb(result);
      } else if (xhr.status == 400) {
        // no entry
        var result = JSON.parse(xhr.responseText);
        cb(result);
      }```
If there is an error you suppose to do something different than when you're ready! am I wrong?!
or you can just send the cb(result) all the time without any conditions!

**Comment by HemaSAli** [comment]
our Api result's contain the code of error (200,400,404)
such as "cod:200" 
so, we can know the code of error from result , after that we can deal with it if it 404 for example , you can see that in dom file

**Comment by IsraaMoqbel** [comment]
but you always return  cb(result);
so whatever the status is you are getting the same result "even though the incoming result is different in each state BUT you're getting this result anyway without the need to make conditions!"
like your condition do nothing additional here!
you can make it useful by sending an error message in the case of error instead of sending the result itself! you can do some validation and error handling here.

**Comment by IsraaMoqbel** [comment]
in your code you only verified    
```
 if (result.cod == 200)
```
and this result is coming for you without these conditions!

**Comment by ali-7** [comment]
we use it for 404, 400 because it returns a JSON object that contain a message we used it in the dom

**Comment by ali-7** [comment]
without these conditions it won't return these messages

**Comment by IsraaMoqbel** [comment]
yeah yeah I see what happen, you can just remove this condition    
```
 if (xhr.status == 200) 
```
and voilà you get your result all the time =D
your function can look like this
```
function fetch(url, cb) {
  var xhr = new XMLHttpRequest();
  xhr.onreadystatechange = function() {
    if (xhr.readyState == 4) {
        var result = JSON.parse(xhr.responseText);
        cb(result);
    }
  };
  xhr.open("GET", url, true);
  xhr.send();
}
```
small and neat =D

**Comment by ali-7** [comment]
yes, it worked for all 200,404,400 , we will fix it tomorrow :smile:
