### ISSUE TITLE
Broken github page link!

### ISSUE THREAD

**Issue by IsraaMoqbel** [FACG5/SSIA-API-WeatherApp#15]
you can just put the index.html file outside the public folder!
and your problem is solved!

**Comment by HemaSAli** [comment]
I really do this in all of my projects !
this time , when mentors talked about file structure , they said that we should put it in public !
by the way , I opposed their idea !

**Comment by IsraaMoqbel** [comment]
Actually there is a way to deploy to github pages without the need to change your file structure and putting your index.html outside, but I never used this method I always prefer the easy straight-forward solutions so I just put it outside the public folder and the life is beautiful :laughing:

**Comment by ali-7** [comment]
@IsraaMoqbel , no need to put the html outside the public file u can access the sit through this link by adding the right directory like this : https://facg5.github.io/SSIA-API-WeatherApp/public/index.html .
but i removed it because it won't work without the api key deployed :smiley:

**Comment by IsraaMoqbel** [comment]
@ali-7 Oh that's cool and easy!
I think there is another way to make it work without the need to change structure but this involve some git commands and I don't know it actually! :smiley:
