### ISSUE TITLE
So there is 5 days of weather prediction! 

### ISSUE THREAD

**Issue by IsraaMoqbel** [FACG5/SSIA-API-WeatherApp#16]
I thought it was 5 hours until I saw your code! :laughing:
So, I think you have to inform the user what the 5 different weather exactly are?! 
like instead of show more button, you can write show the next 5 days of weather or something else you find informative to your user.

**Comment by HemaSAli** [comment]
How did we forget something like this ! 
thanks Israa , we will fix it
