### ISSUE TITLE
Some input validation to avoid bad requests.

### ISSUE THREAD

**Issue by IsraaMoqbel** [FACG5/SSIA-API-WeatherApp#17]
you can use this code to avoid sending an empty or invalid query to the API
which is called Bad request 400 status code
![image](https://user-images.githubusercontent.com/28726665/42892514-ab7a7a08-8aba-11e8-9d7b-402ae51c5a42.png)
    ```if(cityname.value ===""){
      alert('naaah! write something down!')}
else {
fetch(......
}```

so you can avoid making a fetch API request if there is no query data sent!
, you did great thing by displaying "City Not Found !" when there is no result found! :wink: 
but we also want to avoid sending bad requests too =D

**Comment by HemaSAli** [comment]
`  fetch(url, function(result) {`
   ` if (result.cod == 200) {}`
`else{}`

you can see this code in dom.js , so we include 400,404 in "else" , 
i think we forgot to separate 400 and 404

**Comment by IsraaMoqbel** [comment]
I'm talking about preventing the user to send empty queries in your API request, so you inform them by an alert for example that they have to enter something!
I know that you handled your error by displaying city not found for the user in all the cases.

**Comment by ali-7** [comment]
it was there, we try it for 404 and 400 then forget to do the 400 message :smile:

**Comment by IsraaMoqbel** [comment]
@ali-7 sorry, my bad! It actually work for 400 and 404 but the user will not know that he/she has to enter something so it's a kind of informing the user what to do more than handling errors.

**Comment by ali-7** [comment]
@IsraaMoqbel  yes, but 400 return another different message , we try it and forget to do it 
```
cod
:
"400"
message
:
"Nothing to geocode"
```

**Comment by IsraaMoqbel** [comment]
the ```else``` is executed whenever the condition ```result.cod === 200``` is not true so it will be executed in both ```result.cod===400``` and ```result.cod===404```
but to avoid a lot of 400 status code we inform our brilliant user to enter the name of the city he wants to search for =D

**Comment by ali-7** [comment]
or maybe add "City Not Found ! or Wrong Input " or no input

**Comment by IsraaMoqbel** [comment]
Now if you notice in your console you don't get to the point where there is bad requests ```400```, you don't allow the user to get there! because ,in this condition that we add, fetch function will not be executed unless the user has entered something and there is something sent in the query. So now the `city not found` will not appear for the user in the case of 400 status code but only for 404 status code which make more sense!
