### ISSUE TITLE
you can't hide your key from the browser!!

### ISSUE THREAD

**Issue by Eslam3bed** [FACG5/SSIA-API-WeatherApp#28]
https://github.com/FACG5/SSIA-API-WeatherApp/blob/aa2e3629585cfe02570e0e38d7c282e57823f3f4/public/js/dom.js#L22

**Comment by ali-7** [comment]
@Eslam3bed we didn't upload the config file, so the site won't work live, it was explained in the readme .

**Comment by Eslam3bed** [comment]
what's the point?!

**Comment by ali-7** [comment]
it was instructed not deploy your website live if you have an api key, just use it locally, for secure purpose.

**Comment by Eslam3bed** [comment]
I see ...
